-- Seed: Karachi hostel prospects (Gulistan-e-Johar + Gulshan-e-Iqbal)
insert into hms_prospects (name, owner_name, phone, area, address, maps_url, status) values

-- ── GULISTAN-E-JOHAR ─────────────────────────────────────────────────────────
('Lavish Boys Hostel',                         null,                 '+92 331 3968154', 'Gulistan-e-Johar', 'W4CP+7XQ Scheme 36 Block 11 Gulistan-e-Johar, Karachi 74200',                                                                       'https://www.google.com/maps/place/?q=place_id:ChIJB-EI9OY5sz4RN_dc42KvlqE', 'pending'),
('HY Boys Hostel & Rooms for Rent',            null,                 '+92 341 1625992', 'Gulistan-e-Johar', 'H-695 / SA-12, Near Bin Hashim Super Market, Munawar Chowrangi, Block 11 Gulistan-e-Johar, Karachi 75290',                           'https://www.google.com/maps/place/?q=place_id:ChIJNcyYT_A5sz4RYi_0E1IK3Ig', 'pending'),
('Murad Boys Hostel',                          null,                 '+92 306 6473978', 'Gulistan-e-Johar', 'University Hill Road, Block 1 Gulistan-e-Johar, Karachi',                                                                            'https://www.google.com/maps/place/?q=place_id:ChIJt_ze1cE4sz4RbLCavFLEViA', 'pending'),
('Yar Boys Hostel & Rooms For Rent',           null,                 '+92 325 3148005', 'Gulistan-e-Johar', 'Plot 170, Johar Chowrangi Rd, near Kamran Chowrangi Furniture Market, Mughal Hazara Goth Block 4/A Gulistan-e-Johar, Karachi 75290', 'https://www.google.com/maps/place/?q=place_id:ChIJpQpQuKE5sz4RnJ2czuM1tpw', 'pending'),
('Student Housing Hostel (Jauhar Branch)',      'Arsalan Tariq',     '+92 300 2881304', 'Gulistan-e-Johar', 'Block 3-A, Gulistan-e-Johar, Karachi',                                                                                               'https://www.google.com/maps/place/?q=place_id:ChIJ7e0ogIU5sz4R49n7-lBd-s8', 'pending'),
('Rajput Boys Hostel',                         null,                 '+92 300 0226346', 'Gulistan-e-Johar', 'W4CQ+8WV, Scheme 36 Block 11 Gulistan-e-Johar, Karachi',                                                                            'https://www.google.com/maps/place/?q=place_id:ChIJNXXzLAA5sz4R09RZ_1EG2I0', 'pending'),
('Youth Hostel (Boys & Girls)',                null,                 null,              'Gulistan-e-Johar', 'W49C+MXW, St 42, Block 15 Gulistan-e-Johar, Karachi',                                                                               'https://www.google.com/maps/place/?q=place_id:ChIJhyODYgA5sz4R_IoZ-NPJrAk', 'pending'),
('Girls Hostel (Block 14)',                    null,                 '+92 332 3509033', 'Gulistan-e-Johar', 'B-191, Block 14 Gulistan-e-Johar, Karachi 75290',                                                                                    'https://www.google.com/maps/place/?q=place_id:ChIJ2an9MGg5sz4RWC8x3_AL8VU', 'pending'),
('The United Girls Hostel',                   null,                 '+92 333 0033666', 'Gulistan-e-Johar', 'House C-8/1 Street 1, Block 13 Gulistan-e-Johar, Karachi 75290',                                                                     'https://www.google.com/maps/place/?q=place_id:ChIJ02RPsQg5sz4R9mUbu7ko6M4', 'pending'),
('The Nation''s Girls Hostel',                 null,                 '+92 300 8312761', 'Gulistan-e-Johar', 'Bungalow C-160, near Kababjees Bakers, Block 14 Gulistan-e-Johar, Karachi 75290',                                                    'https://www.google.com/maps/place/?q=place_id:ChIJqcSBDbU5sz4R7VjFipi8iGk', 'pending'),
('KyZee Hostels - Girls Branch',               null,                 '+92 306 9559933', 'Gulistan-e-Johar', 'Block 18 Gulistan-e-Johar, Karachi',                                                                                                 'https://www.google.com/maps/place/?q=place_id:ChIJs30WKdU5sz4RhoXpk0uu91U', 'pending'),
('EB Girls Hostel/Accommodations',             null,                 '+92 317 4720852', 'Gulistan-e-Johar', 'Block 20 Gulistan-e-Johar, Karachi 75000',                                                                                           'https://www.google.com/maps/place/?q=place_id:ChIJZwo3uogVsz4RE3b6QeBBkV0', 'pending'),
('Al Jannat Girls Hostel',                    null,                 '+92 335 1316248', 'Gulistan-e-Johar', 'Block C, 211 Block 14, Gulistan-e-Johar, Karachi',                                                                                   'https://www.google.com/maps/place/?q=place_id:ChIJuSI5FwA5sz4RgA4mFCs954Q', 'pending'),

-- ── GULSHAN-E-IQBAL ──────────────────────────────────────────────────────────
('The United Girls Hostel (Gulshan Block 6)',   null,                 '+92 315 2470554', 'Gulshan-e-Iqbal',  'House B-63, Shah Faisal Masjid Rd, Block 6 Gulshan-e-Iqbal, Karachi 75290',                                                          'https://www.google.com/maps/place/?q=place_id:ChIJyW7iB5A5sz4R4wimbc4vRZI', 'pending'),
('Gulshan Boys Hostel',                        null,                 '+92 307 0214210', 'Gulshan-e-Iqbal',  'W3GR+62H, Block 2 Gulshan-e-Iqbal, Karachi',                                                                                         'https://www.google.com/maps/place/?q=place_id:ChIJ4aiyaQA_sz4Rsjivgw2ogA8', 'pending'),
('Al-Haq Boys Hostel',                         null,                 '+92 321 2551558', 'Gulshan-e-Iqbal',  'Block 6 Gulshan-e-Iqbal, Karachi 75300',                                                                                             'https://www.google.com/maps/place/?q=place_id:ChIJ0wN9-z8_sz4Rjfarz7T5de0', 'pending'),
('Student Housing Boys Hostel (Gulshan Branch)','Arsalan Tariq',     '+92 300 2881304', 'Gulshan-e-Iqbal',  'W36H+VJJ, Sahba Akhtar Rd, Block 13D-2 Gulshan-e-Iqbal, Karachi',                                                                   'https://www.google.com/maps/place/?q=place_id:ChIJa0hiWV4_sz4RIQZwNXoeh6c', 'pending'),
('KSO Boys Hostel (Headquarter)',               null,                 null,              'Gulshan-e-Iqbal',  'Gulshan e Iqbal 13B, Block 13 B Gulshan-e-Iqbal, Karachi 75300',                                                                     'https://www.google.com/maps/place/?q=place_id:ChIJo-MtjoU_sz4RUe88GPtsn4M', 'pending'),
('Syed Boys Hostel',                           'Shujahat & Wajahat', '+92 332 3038001', 'Gulshan-e-Iqbal',  'House C-14, C-15, C-16, C-17, Jumma Khan Goth, Hussain Hazara Goth Gulshan-e-Iqbal, Karachi 75300',                                  'https://www.google.com/maps/place/?q=place_id:ChIJU5L9eVk5sz4RcSoOgiZTI4s', 'pending'),
('Iffat Girls University Hostel',              null,                 '+92 301 1164496', 'Gulshan-e-Iqbal',  'Plot C-225, Block 6 Gulshan-e-Iqbal, Karachi',                                                                                       'https://www.google.com/maps/place/?q=place_id:ChIJmZyBNCE5sz4R60Ags4cGSmE', 'pending'),
('Girl''s Hostel (Block 2)',                   null,                 null,              'Gulshan-e-Iqbal',  'Gulshan e Iqbal 13A, Block 2 Gulshan-e-Iqbal, Karachi 75300',                                                                        'https://www.google.com/maps/place/?q=place_id:ChIJD5iUzFg_sz4Rr2h7z1j0IOI', 'pending');
